version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    db:
        image: mysql:5.7.22
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: dvuser
            MYSQL_PASSWORD: root
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
            # - ./.shared:/home/data/db/dumps
            - ./.shared/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./.shared/initTest.sql:/docker-entrypoint-initdb.d/initTest.sql
        ports:
            - "3388:3306"
        networks:
            - laravel

    my_frontend:
        container_name: my_frontend
        image: node:lts
        working_dir: /var/www/html/app/
        entrypoint: /bin/bash
        ports:
            - "9200:9200"
        volumes:
        - ./front/:/var/www/html/app
        tty: true
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
