export const PUSH_CATEGORIES_MUTATION = 'PUSH_CATEGORIES'
export const PUSH_CLIENTS_MUTATION = 'PUSH-CLIENTS'
export const SAVE_CLIENT_MUTATION = 'SAVE_CLIENT'
export const DELETA_CLIENT_MUTATION = 'DELETA_CLIENT'
export const SET_CLIENT_MUTATION = "SET_CLIENT"


export const LIST_CATEGORIES_ACTION = 'LIST_CATEGORIES'
export const LIST_CLIENTS_ACTION = 'LIST_CLIENTS'
export const ADD_CLIENT_ACTION = 'ADD_CLIENT'
export const REMOVE_CLIENT_ACTION = 'REMOVE_CLIENT'
export const UPDATE_CLIENT_ACTION = 'UPDATE_CLIENT'