name: Tests

on:
  push:
    branches: [main]
    paths:
      - docker-compose.yml
      - Dockerfile

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
